name: .NET (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Setup build dependencies
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ 3.1.x, 5.0.x ]
    steps:
      - name: Setup .NET (${{ matrix.dotnet }})
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration $config --no-restore
    - name: Test
      run: dotnet test --configuration $config --no-build --verbosity normal
    - name: Run Client
      run: dotnet "artifacts/bin/Kaylumah.Ssg.Client.SiteGenerator/$config/netcoreapp3.1/Kaylumah.Ssg.Client.SiteGenerator.dll"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-folder
        path: |
          dist

